# Generated by Django 2.0.1 on 2018-06-16 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ownerid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='createby', to=settings.AUTH_USER_MODEL),
        ),
    ]
