# Generated by Django 2.0.1 on 2018-06-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_detail', '0002_auto_20180616_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ownerid',
            new_name='owner',
        ),
    ]
